# -*- coding: utf-8 -*-
"""Class-Progammung-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q4bYMrtOl85_70-L7FtxeD-hPrJ50z8p
"""

#Com bug(erro no programa)
age = int(input("Qual a sua idade? "))

if age >= 18 or age <= 65:
 print("Você pode votar!")
else:
 print("Você não pode votar!")

 #Sem bug(Correto, sem erro)
ageb = int(input("Qual a sua idade? "))

if ageb >= 18 and ageb <= 65:
 print("Você pode votar!")
else:
 print("Você não pode votar!")

# 1: Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.
phrase = "I have a dream that one day this nation will rise up and live out the true meaning of its creed: We hold these truths to be self-evident: that all men are created equal. "
word = input("Qual palavra vc quer por? ")

print(phrase, "", word)

# 2: Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".
hh = input("Que horas são? ")
mm = input("Que minutos são? ")
ss = input("Que segundos são? ")

print("São: ", hh, "horas", mm, "minutos e", ss, "segundos.")

# 3: Declare duas variáveis com números de telefone, incluindo um código de área e o número principal. Concatene esses valores para formar um número de telefone completo.
tel1 = "90543-4537"
tel2 = "90543-4569"
cod1 = "(11)"
cod2 = "(13)"

print("Seu telefone é:", cod1, tel1)
print("Seu telefone é:", cod2, tel2)

# 4: Crie uma lista de ingredientes para uma receita. Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.
list_ingt1 = "Arroz"
list_ingt2 = "Alho"
list_ingt3 = "Cebola"
list_ingt4 = "Óleo"
list_ingt5 = "Cenoura"

print( "Use os seguintes ingredientes:", list_ingt1 + ",",list_ingt2 + ",", list_ingt3 + ",",list_ingt4, "e",list_ingt5 + ".")

# 5: Peça ao usuário para digitar três adjetivos e armazene-os em variáveis. Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.
adj1 = str(input("Escreva um adjetivo: "))
adj2 = str(input("Escreva outro adjetivo: "))
adj3 = str(input("Escreva outro adjetivo: "))

print("Ser bom é ser", adj1, "com isso nos tornamos", adj2, "e por fim o estado de", adj3, "." )