# -*- coding: utf-8 -*-
"""Class-Progamming-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0oxmW_u3MLDDkslsK2jGaB6mzfoT7KW
"""

text = "Hello World"
print(text)

number = 12
name = "Julio"
print( name, "tem", number, "anos de idade.")

number = 1
number2 = 2
number3 = "3"
number4 = 3

#nesta parte nós vamos ver como fazer um comentário,
#mas no caso devemos ver e aprender com a prof, vamos-lá?
# = -> é uma atribuição
# == -> é uma igualdade
# === -> é uma igualdade extrita
# "1" -> classifica um número como texto
if(number >= number2):
  print ("You are Correct")
else:
    print ("You aren't correct")

print (number == number2)
print (number == number3)
print (number == number)
print (number <= number2)
print (number >= number2)
print (number <= number4)

greet = "Hello, "
name = input("What are your name ")
print (greet + name,"!")

# Calculadora 1
number1 = int(input("Digite um Número: "))
operation = input("Qual a expressão: ")
number2 = int(input("Digite um Número: "))


if (operation == "+"):
 print("Esse é o resultado da soma:", number1 + number2)

if (operation == "-"):
 print("Esse é o resultado da subtração:", number1 - number2)

if (operation == "*"):
 print("Esse é o resultado da multiplicação:", number1 * number2)

if (operation == "/"):
 print("Esse é o resultado da divisão:", number1 / number2)

if (operation == "^"):
 print("Esse é o resultado da petenciação", number1 ** number2)

#Atividade 1
number = 3
print(" ")
print("Atividade 1")
print(number*number)

#Atividade 2
nome = "Victor"
sobore = "Richard"
print(" ")
print("Atividade 2")
print(nome +" "+ sobore)

#Atividade 3
print(" ")
print("Atividade 3")
number1 = input("Digite algum número: ")
number2 = input("Digite algum número: ")
print(number1 + number2)

#Atividade 4
python = "python"
num = "3"
print(" ")
print("Atividade 4")
print(python + num)